### ISSUE TITLE
How to set language?

### ISSUE THREAD

**Issue by yoldar** [helpcrunch/helpcrunchsdk-ios#1]
Hi! How to set language? I have created Localizable.strings (Base, Russian, Kazakh) but it takes i18n on from Base file.

**Comment by Fishkiller** [comment]
Hi! How do you test your localization? Any chances this article could help https://medium.com/zendesk-engineering/xcode-quick-tip-testing-your-layout-for-localization-152063dfd7ce ?

**Comment by yoldar** [comment]
Sorry it was like a bug on simulator. On real device it's ok. Thanks!
