### ISSUE TITLE
Navigation bar button items missing when presented from non navigation controller in modal.

### ISSUE THREAD

**Issue by Andrewangeta** [helpcrunch/helpcrunchsdk-ios#12]
Basically while using the SDK and presenting from a non `UINavigationController` the chat sheet shows with the modal presentation. But it turns out that the navigation bar is white and the close buttons don't render properly.

https://user-images.githubusercontent.com/12012815/130278234-155afdbd-281d-4682-a09b-1ae4a23cf99e.MP4

Using the latest 4.0.3 SDK with SPM (Thanks for the update!!)

**Comment by Andrewangeta** [comment]
This could be a good example of how to present or find out if some Apps are using the `UINavigationAppearance` APIs
https://github.com/marmelroy/PhoneNumberKit/blob/1ef0431b971f69c48ca5eb4cdba07f2c5da54c35/PhoneNumberKit/UI/CountryCodePickerViewController.swift#L100-L109

**Comment by Fishkiller** [comment]
Hey, @Andrewangeta , thanks for pointing out! 
Please, check 4.0.4 version. There were a new (iOS 13+) appearance for Navigation bars, that  showed this behaviour. 
I added a fix, so it should be ok now. Please, tell us if the problem is gone

**Comment by Andrewangeta** [comment]
It works as expected! One suggestion though, on the `HelpCrunch.show` call, it'd be nice to optionally pass in `isModalInPresentation` to prefer a gesture dismiss vs an explicit close by tapping on the X in the right bar button. Currently it allows gesture dismissal but the option to configure that would be nice. @Fishkiller

**Comment by Fishkiller** [comment]
@Andrewangeta Sorry for such a long delay, but please, check newest version 4.1.0 . It should fix the problem

**Comment by Andrewangeta** [comment]
Cool will check it out! Thanks for the update!

**Comment by Andrewangeta** [comment]
@Fishkiller Which configuration should I be passing in `isInModalPresentation`?

**Comment by Fishkiller** [comment]
@Andrewangeta It goes directly to **modalInPresentation** property of UIViewController. Try setting `true` to achieve disabling of interactive dissmisal

**Comment by Andrewangeta** [comment]
@Fishkiller  I mean if I'm calling `HelpCrunch.show(..)` I'm not sure what you mean in that context.

**Comment by Fishkiller** [comment]
> @Fishkiller I mean if I'm calling `HelpCrunch.show(..)` I'm not sure what you mean in that context.

Ah, got it. It is property of HCSConfiguration, object that you use to init HelpCrunch in `HelpCrunch.initWith`

**Comment by Andrewangeta** [comment]
Hmmm I keep getting a `Value of type 'HCSConfiguration' has no member 'isInModelPresentation'` and I don't see it in the public `init` either @Fishkiller

**Comment by Fishkiller** [comment]
@Andrewangeta Hm, thats super strange. I just rechecked - it should be in place. Please check if your version is 4.1.0, and can you check HCSConfiguration?
<img width="1065" alt="Screenshot 2021-11-15 at 02 21 22" src="https://user-images.githubusercontent.com/3305980/141705058-32cc17b0-b5d1-48c3-b79b-3885bf775114.png">
 Thats what it should show

**Comment by Andrewangeta** [comment]
Oof misnamed it.

**Comment by Andrewangeta** [comment]
Hmmm still not compiling.

**Comment by Andrewangeta** [comment]
Let me nuke derived data etc.

**Comment by Andrewangeta** [comment]
@Fishkiller  Alright got it. Had some really old cached stuff. it works as expected thanks!
