### ISSUE TITLE
iOS app crashes when switching from knowledge base to chatview

### ISSUE THREAD

**Issue by courierexpert** [helpcrunch/helpcrunchsdk-ios#13]
SDK version ~> 4.0.4

Our app consistently crashes when: 
1) Chatview is open (ok)
2) Switch to knowledge base (ok)
3) Switch back to chatview (crashes)

I'm attempting to use helpcrunchsdk-ios In a [custom capacitor plugin](https://github.com/courierexpert/courierexperthelpcrunch/tree/main/ios)

xCode error:

Courier Expert[3667:685234] *** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <HCSChatViewController 0x1090fb000> for the key path "center" from <UIInputSetHostView 0x108a62340> because it is not registered as an observer.'
*** First throw call stack:
(0x187ce1114 0x19b57dcb4 0x188ea98e4 0x188ea9600 0x10533bd54 0x189e6b3b4 0x189e6bd50 0x189da4a90 0x189e6b3b4 0x189e6bd50 0x189e6cb98 0x18aa16c88 0x18aa15708 0x18aa152d8 0x1052e7c90 0x1052e7aa4 0x18a0acd54 0x18a0b62c8 0x18a0b2f50 0x18a0b2518 0x18a0a6aa8 0x18a0a5e38 0x18a5670fc 0x18a5424fc 0x18a5c476c 0x18a5c8f0c 0x18a5c01cc 0x187c61240 0x187c61140 0x187c60488 0x187c5aa40 0x187c5a200 0x19ddd7598 0x18a523bcc 0x18a5291a0 0x10456203c 0x187939588)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <HCSChatViewController 0x1090fb000> for the key path "center" from <UIInputSetHostView 0x108a62340> because it is not registered as an observer.'
terminating with uncaught exception of type NSException

https://user-images.githubusercontent.com/78301773/132698530-53810609-8255-4bc9-9ac3-a9ecbbe5aee8.mp4

Could I have any advice on what's causing the above crash?

**Comment by Fishkiller** [comment]
@courierexpert please, check newest version 4.1.0 . It should fix the problem

**Comment by courierexpert** [comment]
> @courierexpert please, check newest version 4.1.0 . It should fix the problem

Thanks :) Issue resolved with 4.1.0
