### ISSUE TITLE
Error when po any variable from Xcode Console

### ISSUE THREAD

**Issue by neavery** [helpcrunch/helpcrunchsdk-ios#14]
I get this error when trying `po` any variable in Xcode console when i have added HelpCrunchSDK iOS (v 4.0.4). 

I have currently added HelpCrunch SDK as a SPM but i have also tried adding it with Carthage - got the same type of error.

```
error: virtual filesystem overlay file '/Users/Fishkiller/Library/Developer/Xcode/DerivedData/HelpCrunchSDK-gyynpeopqvemxtewzvgrhfoosadb/Build/Intermediates.noindex/ArchiveIntermediates/HelpCrunchSDK/IntermediateBuildFilesPath/HelpCrunchSDK.build/Release-iphonesimulator/HelpCrunchSDK.build/all-product-headers.yaml' not found
error: module map file '/Users/Fishkiller/Library/Developer/Xcode/DerivedData/HelpCrunchSDK-gyynpeopqvemxtewzvgrhfoosadb/SourcePackages/checkouts/swift-nio-zlib-support/module.modulemap' not found
error: virtual filesystem overlay file '/Users/Fishkiller/Library/Developer/Xcode/DerivedData/HelpCrunchSDK-gyynpeopqvemxtewzvgrhfoosadb/Build/Intermediates.noindex/ArchiveIntermediates/HelpCrunchSDK/IntermediateBuildFilesPath/HelpCrunchSDK.build/Release-iphonesimulator/HelpCrunchSDK.build/all-product-headers.yaml' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```

I have found a similar problem for another project and i think this might help solve my issue here as well. 

_When not using -no-serialize-debugging-options while building frameworks, the package is embedded with absolute paths for search paths etc. from the packaging machine. This would explain the /Users/kylinchang/Library/... path I'm seeing, I guess kylinchang is the one who packaged the framework for FacebookSDK/CoreKit.
Debugging will work on the machine that packaged the framework, but not on any other machine._
From: https://github.com/facebook/facebook-ios-sdk/issues/1628#issuecomment-771462320

**Comment by Fishkiller** [comment]
@neavery please, check newest version 4.1.0 . It should fix the problem

**Comment by neavery** [comment]
Nice @Fishkiller, works like a charm! 👏
