### ISSUE TITLE
Message input disappear after outside tap

### ISSUE THREAD

**Issue by artemmihelson** [helpcrunch/helpcrunchsdk-ios#15]
Hi,

There is an issue with the input field disappearing on outside tap. Reproducible on your demo app on iPhones with notch/dynamic island. On SE and similar screens it is fine. The screencast has been done on simulator but the same behavior is observed on the real device.

![CleanShot 2022-11-01 at 15 01 08](https://user-images.githubusercontent.com/1292542/199239798-62b001b0-1900-4ad2-91cf-c2f18696766b.gif)

**Comment by Fishkiller** [comment]
@artemmihelson Thanks for pointing out! It will be fixed in the upcoming update (will be live soon). I will ping you here, when it be done

**Comment by Fishkiller** [comment]
@artemmihelson Please, check 4.2.2 version. Your issue should be resolved there

**Comment by artemmihelson** [comment]
@Fishkiller thanks for the quick one.
