### ISSUE TITLE
Update user crash on iOS 12.4

### ISSUE THREAD

**Issue by DinuNuta** [helpcrunch/helpcrunchsdk-ios#4]
Hi! When I try to update user, on ios 12.4, the app crash with error: "[NSTaggedPointerString stringValue]: unrecognized selector sent to instance 0x88f7a4ae350d95f7"
iOS app 2.0.12

**Comment by Fishkiller** [comment]
@DinuNuta 
Hi! can you, please, show full method where you're trying to update user?

**Comment by DinuNuta** [comment]
class func registerUser(_ user: UserModel) {
        let userData = HCSUser()
        userData.userId = String(user.id)
        userData.name = user.fullName
        userData.email = user.email
        
        if let phone = user.phone {
            userData.phone = phone
        }
        
        if case UserModel.UserType.company = user.type {
            if let companyName = user.company?.name {
                userData.company = companyName
            }
        }
        HelpCrunch.update(userData, completion: nil)
    }

**Comment by DinuNuta** [comment]
for logout i use :
 HelpCrunch.logout { (error) in
          print(error)
        }

**Comment by Fishkiller** [comment]
Just made a test and couldn't reproduce. Lets try to find where is a problem.

For start: can you breakpoint on  "HelpCrunch.update(user) { (error) in" and check whether all properties in "userData" are correct? Everything should be String (except customData which is Dictionary)

Also it crashes directly on update user or after?

**Comment by DinuNuta** [comment]
Please try test on iOS 12.4:
init  HelpCrunch
update user 
logout
update another user
crash

**Comment by DinuNuta** [comment]
![Screen Shot 2020-03-24 at 01 14 50](https://user-images.githubusercontent.com/22508915/77371885-015daa80-6d6d-11ea-9e44-95fb4de66531.png)
![Screen Shot 2020-03-24 at 01 17 20](https://user-images.githubusercontent.com/22508915/77371988-484ba000-6d6d-11ea-9a17-a03c6ac7a869.png)

**Comment by DinuNuta** [comment]
it's crashes directly on update user

**Comment by Fishkiller** [comment]
Also, can you, please, provide your `organization` name?

**Comment by DinuNuta** [comment]
Organization name : "hastnet"

**Comment by Fishkiller** [comment]
Ok, lets try one more thing. Can you, please, add HCSSDKDEBUGCRITICAL key to info.plist file and set to YES. After that do these steps again and after crash copy/paste everything from console here or (even better) to your portal hastnet.helpcrunch.com and send it there via widget (you can call it by clicking an icon in the bottom-right corner). It will be much easier for us to track progress regarding your issue (and safer)

**Comment by DinuNuta** [comment]
I have send error logs through HelpCrunch via widget. But i haven't received answer yet. Can you help us to solve this issue?
Thanks for your effort.

**Comment by breahna-ebs** [comment]
@Fishkiller Any news here? We cannot release a new version of our app because of this issue.
