### ISSUE TITLE
[iOS] i can't receive notification 

### ISSUE THREAD

**Issue by PacoPacoPakitor** [helpcrunch/helpcrunchsdk-ios#9]
**environment: PROD & Dev
iOS version: 14.4
SDK version: 3.3.4
swift version: 5.3
Xcode version: 12.5** 
 i very sure my APNS it's working fine. cuz my FCM can got notification for the Dev and PROD both environments. and also i has tried with other tool to sent notification, it's also working fine. only helpcrunch it' doesn't get any notification. so the below is my notification set up code. plz let me know which parts i missing or need to be change. thx.

![image](https://user-images.githubusercontent.com/23376484/123226675-11c77c80-d4fe-11eb-9665-17e83358e16e.png)
![image](https://user-images.githubusercontent.com/23376484/123226727-1be97b00-d4fe-11eb-88ea-434d23862e07.png)

**Comment by rkolosovskyi** [comment]
The same valid for me, no notifications in v. 3.2.8, 3.3.1, 3.3.4, 3.3.6
I was able to test this functionality in v. ~3.2.3-3.2.5
APNS certificate and settings for iOS widget the same for all mentioned versions.

**Comment by Fishkiller** [comment]
It should be ok by now
